eedevops/shipyard

- .gitignore
- Makefile
- client/dockerhub.go
- controller/Dockerfile
- controller/api/api.go
- controller/api/dockerhub.go
- controller/api/dockerhub_test.go
- controller/static/app/projects/create.controller.js
- controller/static/app/projects/edit.controller.js
- controller/static/app/projects/projects.service.js
- main.go
- model/dockerhub/image.go
- model/dockerhub/tag.go
Contains the ./controller bugfix as well
> - Cors fix With test coverage

- controller/api/dockerhub.go
Squash of @JonathanRosado error handling of DockerHub API route. Never made it to `dev` in the previous sprint.
> error handling for dockerhub api route.

- controller/static/app/projects/edit.html
> - Switched columns between name and id fields

- controller/static/app/projects/projects.controller.js
- controller/static/app/projects/projects.html
- Fixes #55 
Tool tip feature not included yet.
> - Inspect button will now be disable if the project is not built.

- controller/manager/ilm_builds.go
- controller/manager/ilm_images.go
> Added tags to Results and TestResult related tag fields.

- controller/static/app/projects/edit.html
Partially fixes #53 until a final decision is made
> - Modified tool tip popups to contain a more appropriate description

- controller/static/app/projects/inspect.controller.js
- controller/static/app/projects/inspect.html
> enable inspect action button only if we have test results

- controller/static/app/projects/edit.controller.js
- controller/static/app/projects/edit.html
- controller/static/app/projects/projects.service.js
- controller/static/app/shipyard.jwt.js
> - Fixes flickering loading screen after running multiple tests

- controller/static/app/projects/edit.html
> change tooltip message

- controller/static/app/projects/buildResults.html
> result lines are colored based on the levels Low,Medium,High

- controller/static/app/projects/edit.controller.js
- controller/static/app/projects/edit.html
> - Can now exit test and image modal windows with `esc`

- controller/manager/ilm_builds.go
> - Now supports multi image builds

- docker-compose.yml
> - Modified compose to use the default network

- controller/static/app/projects/buildResults.html
- controller/static/app/projects/inspect.html
> add link to edit view from project results view

- controller/static/app/projects/edit.html
> change labels for add image modal window and add test modal window

- controller/static/app/login/login.html
> set focus to username field

- controller/static/app/projects/projects.controller.js
Fix for project level execution websocket relative path
- Changed websocket to relative URI
> - Changed websocket to relative URI

- Dockerfile-sa.build
- buildme.sh
- create_env_file.sh
- docker-compose.consul.prod.yml
- docker-compose.yml
- ilm-go.build
New ilm-go.build dockerfile, building the image used for building ilm. Image contains golang 1.6.
New Dockerfile-sa.build to build a generic image based on debian.
Updated docker-compose.yml as build, test and deployment are now done via: buildme.sh.
buildme.sh now supports reading environment variables for its internal parameters.
New create_env_file.sh script to create the .env file automatically. Its functionality is included in buildme.sh.
> Stand alone image changes

- controller/static/app/projects/edit.html
- controller/static/app/shipyard.module.js
- controller/static/bower.json
- controller/static/index.html
> fix duplicate image entries from private registry

- docker-compose.agent.consul.yml
- docker-compose.consul.prod.yml
added swarm agent with consul compose file: docker-compose.agent.consul.yml
updated: docker-compose.consul.prod.yml with latest Shipyar's swarm and proxy settings.
> Compose files for our customer - update and addition

- controller/static/app/projects/edit.controller.js
Fixes the UI part of the issue #149
> remove registry id when changing the location

- controller/static/app/projects/edit.controller.js
- controller/static/app/projects/edit.html
> Display image name, tag in the edit modal window

- controller/static/app/projects/edit.html
Disabled additional tags for public registry, both in add and edit image mode, for private registries, this field still is enabled
> Disabled additional tags for public registry, both in add and edit

- client/dockerhub.go
- controller/api/dockerhub.go
- controller/api/dockerhub_test.go
- model/dockerhub/tag.go
Fixed buggy test for dockerhub v2 tags list
> Fixed test for dockerhub v2 tags list

- model/dockerhub/tag.go
> Fixed tags list in model
